version: "3.9"

services:
  app:
    container_name: test-straive-frontend
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - 3000:5173
    volumes:
      - .:/home/app
      - /home/app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    restart: always
